# Generated by Django 3.1.3 on 2021-11-29 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['-id'], 'verbose_name_plural': 'News'},
        ),
    ]
